// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: records_ingest.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RecordIngestService_SendRecords_FullMethodName = "/io.debezium.server.iceberg.rpc.RecordIngestService/SendRecords"
)

// RecordIngestServiceClient is the client API for RecordIngestService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RecordIngestServiceClient interface {
	SendRecords(ctx context.Context, in *IcebergPayload, opts ...grpc.CallOption) (*RecordIngestResponse, error)
}

type recordIngestServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRecordIngestServiceClient(cc grpc.ClientConnInterface) RecordIngestServiceClient {
	return &recordIngestServiceClient{cc}
}

func (c *recordIngestServiceClient) SendRecords(ctx context.Context, in *IcebergPayload, opts ...grpc.CallOption) (*RecordIngestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecordIngestResponse)
	err := c.cc.Invoke(ctx, RecordIngestService_SendRecords_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RecordIngestServiceServer is the server API for RecordIngestService service.
// All implementations must embed UnimplementedRecordIngestServiceServer
// for forward compatibility.
type RecordIngestServiceServer interface {
	SendRecords(context.Context, *IcebergPayload) (*RecordIngestResponse, error)
	mustEmbedUnimplementedRecordIngestServiceServer()
}

// UnimplementedRecordIngestServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRecordIngestServiceServer struct{}

func (UnimplementedRecordIngestServiceServer) SendRecords(context.Context, *IcebergPayload) (*RecordIngestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendRecords not implemented")
}
func (UnimplementedRecordIngestServiceServer) mustEmbedUnimplementedRecordIngestServiceServer() {}
func (UnimplementedRecordIngestServiceServer) testEmbeddedByValue()                             {}

// UnsafeRecordIngestServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RecordIngestServiceServer will
// result in compilation errors.
type UnsafeRecordIngestServiceServer interface {
	mustEmbedUnimplementedRecordIngestServiceServer()
}

func RegisterRecordIngestServiceServer(s grpc.ServiceRegistrar, srv RecordIngestServiceServer) {
	// If the following call panics, it indicates UnimplementedRecordIngestServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RecordIngestService_ServiceDesc, srv)
}

func _RecordIngestService_SendRecords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IcebergPayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordIngestServiceServer).SendRecords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecordIngestService_SendRecords_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordIngestServiceServer).SendRecords(ctx, req.(*IcebergPayload))
	}
	return interceptor(ctx, in, info, handler)
}

// RecordIngestService_ServiceDesc is the grpc.ServiceDesc for RecordIngestService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RecordIngestService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "io.debezium.server.iceberg.rpc.RecordIngestService",
	HandlerType: (*RecordIngestServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendRecords",
			Handler:    _RecordIngestService_SendRecords_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "records_ingest.proto",
}

const (
	ArrowIngestService_IcebergAPI_FullMethodName = "/io.debezium.server.iceberg.rpc.ArrowIngestService/IcebergAPI"
)

// ArrowIngestServiceClient is the client API for ArrowIngestService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ArrowIngestServiceClient interface {
	IcebergAPI(ctx context.Context, in *ArrowPayload, opts ...grpc.CallOption) (*ArrowIngestResponse, error)
}

type arrowIngestServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewArrowIngestServiceClient(cc grpc.ClientConnInterface) ArrowIngestServiceClient {
	return &arrowIngestServiceClient{cc}
}

func (c *arrowIngestServiceClient) IcebergAPI(ctx context.Context, in *ArrowPayload, opts ...grpc.CallOption) (*ArrowIngestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ArrowIngestResponse)
	err := c.cc.Invoke(ctx, ArrowIngestService_IcebergAPI_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ArrowIngestServiceServer is the server API for ArrowIngestService service.
// All implementations must embed UnimplementedArrowIngestServiceServer
// for forward compatibility.
type ArrowIngestServiceServer interface {
	IcebergAPI(context.Context, *ArrowPayload) (*ArrowIngestResponse, error)
	mustEmbedUnimplementedArrowIngestServiceServer()
}

// UnimplementedArrowIngestServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedArrowIngestServiceServer struct{}

func (UnimplementedArrowIngestServiceServer) IcebergAPI(context.Context, *ArrowPayload) (*ArrowIngestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IcebergAPI not implemented")
}
func (UnimplementedArrowIngestServiceServer) mustEmbedUnimplementedArrowIngestServiceServer() {}
func (UnimplementedArrowIngestServiceServer) testEmbeddedByValue()                            {}

// UnsafeArrowIngestServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ArrowIngestServiceServer will
// result in compilation errors.
type UnsafeArrowIngestServiceServer interface {
	mustEmbedUnimplementedArrowIngestServiceServer()
}

func RegisterArrowIngestServiceServer(s grpc.ServiceRegistrar, srv ArrowIngestServiceServer) {
	// If the following call panics, it indicates UnimplementedArrowIngestServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ArrowIngestService_ServiceDesc, srv)
}

func _ArrowIngestService_IcebergAPI_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArrowPayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArrowIngestServiceServer).IcebergAPI(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArrowIngestService_IcebergAPI_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArrowIngestServiceServer).IcebergAPI(ctx, req.(*ArrowPayload))
	}
	return interceptor(ctx, in, info, handler)
}

// ArrowIngestService_ServiceDesc is the grpc.ServiceDesc for ArrowIngestService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ArrowIngestService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "io.debezium.server.iceberg.rpc.ArrowIngestService",
	HandlerType: (*ArrowIngestServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IcebergAPI",
			Handler:    _ArrowIngestService_IcebergAPI_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "records_ingest.proto",
}
