// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: records_ingest.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IcebergPayload_PayloadType int32

const (
	IcebergPayload_RECORDS              IcebergPayload_PayloadType = 0
	IcebergPayload_COMMIT               IcebergPayload_PayloadType = 1
	IcebergPayload_EVOLVE_SCHEMA        IcebergPayload_PayloadType = 2
	IcebergPayload_DROP_TABLE           IcebergPayload_PayloadType = 3
	IcebergPayload_GET_OR_CREATE_TABLE  IcebergPayload_PayloadType = 4
	IcebergPayload_REFRESH_TABLE_SCHEMA IcebergPayload_PayloadType = 5
	IcebergPayload_CLOSE_SESSION        IcebergPayload_PayloadType = 6
)

// Enum value maps for IcebergPayload_PayloadType.
var (
	IcebergPayload_PayloadType_name = map[int32]string{
		0: "RECORDS",
		1: "COMMIT",
		2: "EVOLVE_SCHEMA",
		3: "DROP_TABLE",
		4: "GET_OR_CREATE_TABLE",
		5: "REFRESH_TABLE_SCHEMA",
		6: "CLOSE_SESSION",
	}
	IcebergPayload_PayloadType_value = map[string]int32{
		"RECORDS":              0,
		"COMMIT":               1,
		"EVOLVE_SCHEMA":        2,
		"DROP_TABLE":           3,
		"GET_OR_CREATE_TABLE":  4,
		"REFRESH_TABLE_SCHEMA": 5,
		"CLOSE_SESSION":        6,
	}
)

func (x IcebergPayload_PayloadType) Enum() *IcebergPayload_PayloadType {
	p := new(IcebergPayload_PayloadType)
	*p = x
	return p
}

func (x IcebergPayload_PayloadType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IcebergPayload_PayloadType) Descriptor() protoreflect.EnumDescriptor {
	return file_records_ingest_proto_enumTypes[0].Descriptor()
}

func (IcebergPayload_PayloadType) Type() protoreflect.EnumType {
	return &file_records_ingest_proto_enumTypes[0]
}

func (x IcebergPayload_PayloadType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IcebergPayload_PayloadType.Descriptor instead.
func (IcebergPayload_PayloadType) EnumDescriptor() ([]byte, []int) {
	return file_records_ingest_proto_rawDescGZIP(), []int{0, 0}
}

type ArrowPayload_PayloadType int32

const (
	ArrowPayload_UPLOAD_FILE         ArrowPayload_PayloadType = 0
	ArrowPayload_REGISTER_AND_COMMIT ArrowPayload_PayloadType = 1
	ArrowPayload_JSONSCHEMA          ArrowPayload_PayloadType = 2
	ArrowPayload_FILEPATH            ArrowPayload_PayloadType = 3
)

// Enum value maps for ArrowPayload_PayloadType.
var (
	ArrowPayload_PayloadType_name = map[int32]string{
		0: "UPLOAD_FILE",
		1: "REGISTER_AND_COMMIT",
		2: "JSONSCHEMA",
		3: "FILEPATH",
	}
	ArrowPayload_PayloadType_value = map[string]int32{
		"UPLOAD_FILE":         0,
		"REGISTER_AND_COMMIT": 1,
		"JSONSCHEMA":          2,
		"FILEPATH":            3,
	}
)

func (x ArrowPayload_PayloadType) Enum() *ArrowPayload_PayloadType {
	p := new(ArrowPayload_PayloadType)
	*p = x
	return p
}

func (x ArrowPayload_PayloadType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ArrowPayload_PayloadType) Descriptor() protoreflect.EnumDescriptor {
	return file_records_ingest_proto_enumTypes[1].Descriptor()
}

func (ArrowPayload_PayloadType) Type() protoreflect.EnumType {
	return &file_records_ingest_proto_enumTypes[1]
}

func (x ArrowPayload_PayloadType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ArrowPayload_PayloadType.Descriptor instead.
func (ArrowPayload_PayloadType) EnumDescriptor() ([]byte, []int) {
	return file_records_ingest_proto_rawDescGZIP(), []int{2, 0}
}

type IcebergPayload struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Type          IcebergPayload_PayloadType  `protobuf:"varint,1,opt,name=type,proto3,enum=io.debezium.server.iceberg.rpc.IcebergPayload_PayloadType" json:"type,omitempty"`
	Metadata      *IcebergPayload_Metadata    `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Records       []*IcebergPayload_IceRecord `protobuf:"bytes,3,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IcebergPayload) Reset() {
	*x = IcebergPayload{}
	mi := &file_records_ingest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IcebergPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IcebergPayload) ProtoMessage() {}

func (x *IcebergPayload) ProtoReflect() protoreflect.Message {
	mi := &file_records_ingest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IcebergPayload.ProtoReflect.Descriptor instead.
func (*IcebergPayload) Descriptor() ([]byte, []int) {
	return file_records_ingest_proto_rawDescGZIP(), []int{0}
}

func (x *IcebergPayload) GetType() IcebergPayload_PayloadType {
	if x != nil {
		return x.Type
	}
	return IcebergPayload_RECORDS
}

func (x *IcebergPayload) GetMetadata() *IcebergPayload_Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *IcebergPayload) GetRecords() []*IcebergPayload_IceRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

type RecordIngestResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Result         string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Success        bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`                                   // Adding success boolean for better error handling
	Olake_2PcState string                 `protobuf:"bytes,3,opt,name=olake_2pc_state,json=olake2pcState,proto3" json:"olake_2pc_state,omitempty"` // GET_OR_CREATE_TABLE: 2PC state JSON from table metadata
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RecordIngestResponse) Reset() {
	*x = RecordIngestResponse{}
	mi := &file_records_ingest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordIngestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordIngestResponse) ProtoMessage() {}

func (x *RecordIngestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_records_ingest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordIngestResponse.ProtoReflect.Descriptor instead.
func (*RecordIngestResponse) Descriptor() ([]byte, []int) {
	return file_records_ingest_proto_rawDescGZIP(), []int{1}
}

func (x *RecordIngestResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *RecordIngestResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RecordIngestResponse) GetOlake_2PcState() string {
	if x != nil {
		return x.Olake_2PcState
	}
	return ""
}

type ArrowPayload struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Type          ArrowPayload_PayloadType `protobuf:"varint,1,opt,name=type,proto3,enum=io.debezium.server.iceberg.rpc.ArrowPayload_PayloadType" json:"type,omitempty"`
	Metadata      *ArrowPayload_Metadata   `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArrowPayload) Reset() {
	*x = ArrowPayload{}
	mi := &file_records_ingest_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArrowPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArrowPayload) ProtoMessage() {}

func (x *ArrowPayload) ProtoReflect() protoreflect.Message {
	mi := &file_records_ingest_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArrowPayload.ProtoReflect.Descriptor instead.
func (*ArrowPayload) Descriptor() ([]byte, []int) {
	return file_records_ingest_proto_rawDescGZIP(), []int{2}
}

func (x *ArrowPayload) GetType() ArrowPayload_PayloadType {
	if x != nil {
		return x.Type
	}
	return ArrowPayload_UPLOAD_FILE
}

func (x *ArrowPayload) GetMetadata() *ArrowPayload_Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ArrowIngestResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Result         string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	IcebergSchemas map[string]string      `protobuf:"bytes,2,rep,name=icebergSchemas,proto3" json:"icebergSchemas,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ArrowIngestResponse) Reset() {
	*x = ArrowIngestResponse{}
	mi := &file_records_ingest_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArrowIngestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArrowIngestResponse) ProtoMessage() {}

func (x *ArrowIngestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_records_ingest_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArrowIngestResponse.ProtoReflect.Descriptor instead.
func (*ArrowIngestResponse) Descriptor() ([]byte, []int) {
	return file_records_ingest_proto_rawDescGZIP(), []int{3}
}

func (x *ArrowIngestResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *ArrowIngestResponse) GetIcebergSchemas() map[string]string {
	if x != nil {
		return x.IcebergSchemas
	}
	return nil
}

type IcebergPayload_Metadata struct {
	state           protoimpl.MessageState        `protogen:"open.v1"`
	DestTableName   string                        `protobuf:"bytes,1,opt,name=dest_table_name,json=destTableName,proto3" json:"dest_table_name,omitempty"`
	ThreadId        string                        `protobuf:"bytes,2,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	IdentifierField *string                       `protobuf:"bytes,3,opt,name=identifier_field,json=identifierField,proto3,oneof" json:"identifier_field,omitempty"`
	Schema          []*IcebergPayload_SchemaField `protobuf:"bytes,4,rep,name=schema,proto3" json:"schema,omitempty"`
	Payload         string                        `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"`
	// Per-stream context (previously baked into JVM CLI args)
	Namespace       string                           `protobuf:"bytes,7,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Upsert          bool                             `protobuf:"varint,8,opt,name=upsert,proto3" json:"upsert,omitempty"`
	PartitionFields []*IcebergPayload_PartitionField `protobuf:"bytes,10,rep,name=partition_fields,json=partitionFields,proto3" json:"partition_fields,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *IcebergPayload_Metadata) Reset() {
	*x = IcebergPayload_Metadata{}
	mi := &file_records_ingest_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IcebergPayload_Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IcebergPayload_Metadata) ProtoMessage() {}

func (x *IcebergPayload_Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_records_ingest_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IcebergPayload_Metadata.ProtoReflect.Descriptor instead.
func (*IcebergPayload_Metadata) Descriptor() ([]byte, []int) {
	return file_records_ingest_proto_rawDescGZIP(), []int{0, 0}
}

func (x *IcebergPayload_Metadata) GetDestTableName() string {
	if x != nil {
		return x.DestTableName
	}
	return ""
}

func (x *IcebergPayload_Metadata) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

func (x *IcebergPayload_Metadata) GetIdentifierField() string {
	if x != nil && x.IdentifierField != nil {
		return *x.IdentifierField
	}
	return ""
}

func (x *IcebergPayload_Metadata) GetSchema() []*IcebergPayload_SchemaField {
	if x != nil {
		return x.Schema
	}
	return nil
}

func (x *IcebergPayload_Metadata) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *IcebergPayload_Metadata) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *IcebergPayload_Metadata) GetUpsert() bool {
	if x != nil {
		return x.Upsert
	}
	return false
}

func (x *IcebergPayload_Metadata) GetPartitionFields() []*IcebergPayload_PartitionField {
	if x != nil {
		return x.PartitionFields
	}
	return nil
}

type IcebergPayload_SchemaField struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IceType       string                 `protobuf:"bytes,1,opt,name=ice_type,json=iceType,proto3" json:"ice_type,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IcebergPayload_SchemaField) Reset() {
	*x = IcebergPayload_SchemaField{}
	mi := &file_records_ingest_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IcebergPayload_SchemaField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IcebergPayload_SchemaField) ProtoMessage() {}

func (x *IcebergPayload_SchemaField) ProtoReflect() protoreflect.Message {
	mi := &file_records_ingest_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IcebergPayload_SchemaField.ProtoReflect.Descriptor instead.
func (*IcebergPayload_SchemaField) Descriptor() ([]byte, []int) {
	return file_records_ingest_proto_rawDescGZIP(), []int{0, 1}
}

func (x *IcebergPayload_SchemaField) GetIceType() string {
	if x != nil {
		return x.IceType
	}
	return ""
}

func (x *IcebergPayload_SchemaField) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type IcebergPayload_PartitionField struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Transform     string                 `protobuf:"bytes,2,opt,name=transform,proto3" json:"transform,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IcebergPayload_PartitionField) Reset() {
	*x = IcebergPayload_PartitionField{}
	mi := &file_records_ingest_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IcebergPayload_PartitionField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IcebergPayload_PartitionField) ProtoMessage() {}

func (x *IcebergPayload_PartitionField) ProtoReflect() protoreflect.Message {
	mi := &file_records_ingest_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IcebergPayload_PartitionField.ProtoReflect.Descriptor instead.
func (*IcebergPayload_PartitionField) Descriptor() ([]byte, []int) {
	return file_records_ingest_proto_rawDescGZIP(), []int{0, 2}
}

func (x *IcebergPayload_PartitionField) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *IcebergPayload_PartitionField) GetTransform() string {
	if x != nil {
		return x.Transform
	}
	return ""
}

// OPTIMIZED: Replace google.protobuf.Value with typed fields
type IcebergPayload_IceRecord struct {
	state         protoimpl.MessageState                 `protogen:"open.v1"`
	Fields        []*IcebergPayload_IceRecord_FieldValue `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"`
	RecordType    string                                 `protobuf:"bytes,2,opt,name=record_type,json=recordType,proto3" json:"record_type,omitempty"` // "u", "c", "r"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IcebergPayload_IceRecord) Reset() {
	*x = IcebergPayload_IceRecord{}
	mi := &file_records_ingest_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IcebergPayload_IceRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IcebergPayload_IceRecord) ProtoMessage() {}

func (x *IcebergPayload_IceRecord) ProtoReflect() protoreflect.Message {
	mi := &file_records_ingest_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IcebergPayload_IceRecord.ProtoReflect.Descriptor instead.
func (*IcebergPayload_IceRecord) Descriptor() ([]byte, []int) {
	return file_records_ingest_proto_rawDescGZIP(), []int{0, 3}
}

func (x *IcebergPayload_IceRecord) GetFields() []*IcebergPayload_IceRecord_FieldValue {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *IcebergPayload_IceRecord) GetRecordType() string {
	if x != nil {
		return x.RecordType
	}
	return ""
}

// Use oneof for efficient memory usage - only one field type active per record field
type IcebergPayload_IceRecord_FieldValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*IcebergPayload_IceRecord_FieldValue_StringValue
	//	*IcebergPayload_IceRecord_FieldValue_IntValue
	//	*IcebergPayload_IceRecord_FieldValue_LongValue
	//	*IcebergPayload_IceRecord_FieldValue_FloatValue
	//	*IcebergPayload_IceRecord_FieldValue_DoubleValue
	//	*IcebergPayload_IceRecord_FieldValue_BoolValue
	//	*IcebergPayload_IceRecord_FieldValue_BytesValue
	Value         isIcebergPayload_IceRecord_FieldValue_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IcebergPayload_IceRecord_FieldValue) Reset() {
	*x = IcebergPayload_IceRecord_FieldValue{}
	mi := &file_records_ingest_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IcebergPayload_IceRecord_FieldValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IcebergPayload_IceRecord_FieldValue) ProtoMessage() {}

func (x *IcebergPayload_IceRecord_FieldValue) ProtoReflect() protoreflect.Message {
	mi := &file_records_ingest_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IcebergPayload_IceRecord_FieldValue.ProtoReflect.Descriptor instead.
func (*IcebergPayload_IceRecord_FieldValue) Descriptor() ([]byte, []int) {
	return file_records_ingest_proto_rawDescGZIP(), []int{0, 3, 0}
}

func (x *IcebergPayload_IceRecord_FieldValue) GetValue() isIcebergPayload_IceRecord_FieldValue_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *IcebergPayload_IceRecord_FieldValue) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*IcebergPayload_IceRecord_FieldValue_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *IcebergPayload_IceRecord_FieldValue) GetIntValue() int32 {
	if x != nil {
		if x, ok := x.Value.(*IcebergPayload_IceRecord_FieldValue_IntValue); ok {
			return x.IntValue
		}
	}
	return 0
}

func (x *IcebergPayload_IceRecord_FieldValue) GetLongValue() int64 {
	if x != nil {
		if x, ok := x.Value.(*IcebergPayload_IceRecord_FieldValue_LongValue); ok {
			return x.LongValue
		}
	}
	return 0
}

func (x *IcebergPayload_IceRecord_FieldValue) GetFloatValue() float32 {
	if x != nil {
		if x, ok := x.Value.(*IcebergPayload_IceRecord_FieldValue_FloatValue); ok {
			return x.FloatValue
		}
	}
	return 0
}

func (x *IcebergPayload_IceRecord_FieldValue) GetDoubleValue() float64 {
	if x != nil {
		if x, ok := x.Value.(*IcebergPayload_IceRecord_FieldValue_DoubleValue); ok {
			return x.DoubleValue
		}
	}
	return 0
}

func (x *IcebergPayload_IceRecord_FieldValue) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Value.(*IcebergPayload_IceRecord_FieldValue_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *IcebergPayload_IceRecord_FieldValue) GetBytesValue() []byte {
	if x != nil {
		if x, ok := x.Value.(*IcebergPayload_IceRecord_FieldValue_BytesValue); ok {
			return x.BytesValue
		}
	}
	return nil
}

type isIcebergPayload_IceRecord_FieldValue_Value interface {
	isIcebergPayload_IceRecord_FieldValue_Value()
}

type IcebergPayload_IceRecord_FieldValue_StringValue struct {
	StringValue string `protobuf:"bytes,1,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type IcebergPayload_IceRecord_FieldValue_IntValue struct {
	IntValue int32 `protobuf:"varint,2,opt,name=int_value,json=intValue,proto3,oneof"`
}

type IcebergPayload_IceRecord_FieldValue_LongValue struct {
	LongValue int64 `protobuf:"varint,3,opt,name=long_value,json=longValue,proto3,oneof"`
}

type IcebergPayload_IceRecord_FieldValue_FloatValue struct {
	FloatValue float32 `protobuf:"fixed32,4,opt,name=float_value,json=floatValue,proto3,oneof"`
}

type IcebergPayload_IceRecord_FieldValue_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,5,opt,name=double_value,json=doubleValue,proto3,oneof"`
}

type IcebergPayload_IceRecord_FieldValue_BoolValue struct {
	BoolValue bool `protobuf:"varint,6,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type IcebergPayload_IceRecord_FieldValue_BytesValue struct {
	BytesValue []byte `protobuf:"bytes,7,opt,name=bytes_value,json=bytesValue,proto3,oneof"`
}

func (*IcebergPayload_IceRecord_FieldValue_StringValue) isIcebergPayload_IceRecord_FieldValue_Value() {
}

func (*IcebergPayload_IceRecord_FieldValue_IntValue) isIcebergPayload_IceRecord_FieldValue_Value() {}

func (*IcebergPayload_IceRecord_FieldValue_LongValue) isIcebergPayload_IceRecord_FieldValue_Value() {}

func (*IcebergPayload_IceRecord_FieldValue_FloatValue) isIcebergPayload_IceRecord_FieldValue_Value() {
}

func (*IcebergPayload_IceRecord_FieldValue_DoubleValue) isIcebergPayload_IceRecord_FieldValue_Value() {
}

func (*IcebergPayload_IceRecord_FieldValue_BoolValue) isIcebergPayload_IceRecord_FieldValue_Value() {}

func (*IcebergPayload_IceRecord_FieldValue_BytesValue) isIcebergPayload_IceRecord_FieldValue_Value() {
}

type ArrowPayload_FileMetadata struct {
	state           protoimpl.MessageState                      `protogen:"open.v1"`
	FileType        string                                      `protobuf:"bytes,1,opt,name=file_type,json=fileType,proto3" json:"file_type,omitempty"`
	FilePath        string                                      `protobuf:"bytes,2,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	RecordCount     int64                                       `protobuf:"varint,3,opt,name=record_count,json=recordCount,proto3" json:"record_count,omitempty"`
	PartitionValues []*ArrowPayload_FileMetadata_PartitionValue `protobuf:"bytes,5,rep,name=partition_values,json=partitionValues,proto3" json:"partition_values,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ArrowPayload_FileMetadata) Reset() {
	*x = ArrowPayload_FileMetadata{}
	mi := &file_records_ingest_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArrowPayload_FileMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArrowPayload_FileMetadata) ProtoMessage() {}

func (x *ArrowPayload_FileMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_records_ingest_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArrowPayload_FileMetadata.ProtoReflect.Descriptor instead.
func (*ArrowPayload_FileMetadata) Descriptor() ([]byte, []int) {
	return file_records_ingest_proto_rawDescGZIP(), []int{2, 0}
}

func (x *ArrowPayload_FileMetadata) GetFileType() string {
	if x != nil {
		return x.FileType
	}
	return ""
}

func (x *ArrowPayload_FileMetadata) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *ArrowPayload_FileMetadata) GetRecordCount() int64 {
	if x != nil {
		return x.RecordCount
	}
	return 0
}

func (x *ArrowPayload_FileMetadata) GetPartitionValues() []*ArrowPayload_FileMetadata_PartitionValue {
	if x != nil {
		return x.PartitionValues
	}
	return nil
}

type ArrowPayload_FileUploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileData      []byte                 `protobuf:"bytes,1,opt,name=file_data,json=fileData,proto3" json:"file_data,omitempty"`
	FilePath      string                 `protobuf:"bytes,2,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArrowPayload_FileUploadRequest) Reset() {
	*x = ArrowPayload_FileUploadRequest{}
	mi := &file_records_ingest_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArrowPayload_FileUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArrowPayload_FileUploadRequest) ProtoMessage() {}

func (x *ArrowPayload_FileUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_records_ingest_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArrowPayload_FileUploadRequest.ProtoReflect.Descriptor instead.
func (*ArrowPayload_FileUploadRequest) Descriptor() ([]byte, []int) {
	return file_records_ingest_proto_rawDescGZIP(), []int{2, 1}
}

func (x *ArrowPayload_FileUploadRequest) GetFileData() []byte {
	if x != nil {
		return x.FileData
	}
	return nil
}

func (x *ArrowPayload_FileUploadRequest) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

type ArrowPayload_Metadata struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	DestTableName string                          `protobuf:"bytes,1,opt,name=dest_table_name,json=destTableName,proto3" json:"dest_table_name,omitempty"`
	ThreadId      string                          `protobuf:"bytes,2,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	FileMetadata  []*ArrowPayload_FileMetadata    `protobuf:"bytes,3,rep,name=file_metadata,json=fileMetadata,proto3" json:"file_metadata,omitempty"`
	FileUpload    *ArrowPayload_FileUploadRequest `protobuf:"bytes,4,opt,name=file_upload,json=fileUpload,proto3,oneof" json:"file_upload,omitempty"`
	Payload       string                          `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArrowPayload_Metadata) Reset() {
	*x = ArrowPayload_Metadata{}
	mi := &file_records_ingest_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArrowPayload_Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArrowPayload_Metadata) ProtoMessage() {}

func (x *ArrowPayload_Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_records_ingest_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArrowPayload_Metadata.ProtoReflect.Descriptor instead.
func (*ArrowPayload_Metadata) Descriptor() ([]byte, []int) {
	return file_records_ingest_proto_rawDescGZIP(), []int{2, 2}
}

func (x *ArrowPayload_Metadata) GetDestTableName() string {
	if x != nil {
		return x.DestTableName
	}
	return ""
}

func (x *ArrowPayload_Metadata) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

func (x *ArrowPayload_Metadata) GetFileMetadata() []*ArrowPayload_FileMetadata {
	if x != nil {
		return x.FileMetadata
	}
	return nil
}

func (x *ArrowPayload_Metadata) GetFileUpload() *ArrowPayload_FileUploadRequest {
	if x != nil {
		return x.FileUpload
	}
	return nil
}

func (x *ArrowPayload_Metadata) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

type ArrowPayload_FileMetadata_PartitionValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*ArrowPayload_FileMetadata_PartitionValue_IntValue
	//	*ArrowPayload_FileMetadata_PartitionValue_LongValue
	//	*ArrowPayload_FileMetadata_PartitionValue_StringValue
	//	*ArrowPayload_FileMetadata_PartitionValue_FloatValue
	//	*ArrowPayload_FileMetadata_PartitionValue_DoubleValue
	//	*ArrowPayload_FileMetadata_PartitionValue_BoolValue
	Value         isArrowPayload_FileMetadata_PartitionValue_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArrowPayload_FileMetadata_PartitionValue) Reset() {
	*x = ArrowPayload_FileMetadata_PartitionValue{}
	mi := &file_records_ingest_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArrowPayload_FileMetadata_PartitionValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArrowPayload_FileMetadata_PartitionValue) ProtoMessage() {}

func (x *ArrowPayload_FileMetadata_PartitionValue) ProtoReflect() protoreflect.Message {
	mi := &file_records_ingest_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArrowPayload_FileMetadata_PartitionValue.ProtoReflect.Descriptor instead.
func (*ArrowPayload_FileMetadata_PartitionValue) Descriptor() ([]byte, []int) {
	return file_records_ingest_proto_rawDescGZIP(), []int{2, 0, 0}
}

func (x *ArrowPayload_FileMetadata_PartitionValue) GetValue() isArrowPayload_FileMetadata_PartitionValue_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *ArrowPayload_FileMetadata_PartitionValue) GetIntValue() int32 {
	if x != nil {
		if x, ok := x.Value.(*ArrowPayload_FileMetadata_PartitionValue_IntValue); ok {
			return x.IntValue
		}
	}
	return 0
}

func (x *ArrowPayload_FileMetadata_PartitionValue) GetLongValue() int64 {
	if x != nil {
		if x, ok := x.Value.(*ArrowPayload_FileMetadata_PartitionValue_LongValue); ok {
			return x.LongValue
		}
	}
	return 0
}

func (x *ArrowPayload_FileMetadata_PartitionValue) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*ArrowPayload_FileMetadata_PartitionValue_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *ArrowPayload_FileMetadata_PartitionValue) GetFloatValue() float32 {
	if x != nil {
		if x, ok := x.Value.(*ArrowPayload_FileMetadata_PartitionValue_FloatValue); ok {
			return x.FloatValue
		}
	}
	return 0
}

func (x *ArrowPayload_FileMetadata_PartitionValue) GetDoubleValue() float64 {
	if x != nil {
		if x, ok := x.Value.(*ArrowPayload_FileMetadata_PartitionValue_DoubleValue); ok {
			return x.DoubleValue
		}
	}
	return 0
}

func (x *ArrowPayload_FileMetadata_PartitionValue) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Value.(*ArrowPayload_FileMetadata_PartitionValue_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

type isArrowPayload_FileMetadata_PartitionValue_Value interface {
	isArrowPayload_FileMetadata_PartitionValue_Value()
}

type ArrowPayload_FileMetadata_PartitionValue_IntValue struct {
	IntValue int32 `protobuf:"varint,1,opt,name=int_value,json=intValue,proto3,oneof"`
}

type ArrowPayload_FileMetadata_PartitionValue_LongValue struct {
	LongValue int64 `protobuf:"varint,2,opt,name=long_value,json=longValue,proto3,oneof"`
}

type ArrowPayload_FileMetadata_PartitionValue_StringValue struct {
	StringValue string `protobuf:"bytes,3,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type ArrowPayload_FileMetadata_PartitionValue_FloatValue struct {
	FloatValue float32 `protobuf:"fixed32,4,opt,name=float_value,json=floatValue,proto3,oneof"`
}

type ArrowPayload_FileMetadata_PartitionValue_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,5,opt,name=double_value,json=doubleValue,proto3,oneof"`
}

type ArrowPayload_FileMetadata_PartitionValue_BoolValue struct {
	BoolValue bool `protobuf:"varint,6,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

func (*ArrowPayload_FileMetadata_PartitionValue_IntValue) isArrowPayload_FileMetadata_PartitionValue_Value() {
}

func (*ArrowPayload_FileMetadata_PartitionValue_LongValue) isArrowPayload_FileMetadata_PartitionValue_Value() {
}

func (*ArrowPayload_FileMetadata_PartitionValue_StringValue) isArrowPayload_FileMetadata_PartitionValue_Value() {
}

func (*ArrowPayload_FileMetadata_PartitionValue_FloatValue) isArrowPayload_FileMetadata_PartitionValue_Value() {
}

func (*ArrowPayload_FileMetadata_PartitionValue_DoubleValue) isArrowPayload_FileMetadata_PartitionValue_Value() {
}

func (*ArrowPayload_FileMetadata_PartitionValue_BoolValue) isArrowPayload_FileMetadata_PartitionValue_Value() {
}

var File_records_ingest_proto protoreflect.FileDescriptor

const file_records_ingest_proto_rawDesc = "" +
	"\n" +
	"\x14records_ingest.proto\x12\x1eio.debezium.server.iceberg.rpc\"\xd7\n" +
	"\n" +
	"\x0eIcebergPayload\x12N\n" +
	"\x04type\x18\x01 \x01(\x0e2:.io.debezium.server.iceberg.rpc.IcebergPayload.PayloadTypeR\x04type\x12S\n" +
	"\bmetadata\x18\x02 \x01(\v27.io.debezium.server.iceberg.rpc.IcebergPayload.MetadataR\bmetadata\x12R\n" +
	"\arecords\x18\x03 \x03(\v28.io.debezium.server.iceberg.rpc.IcebergPayload.IceRecordR\arecords\x1a\xa2\x03\n" +
	"\bMetadata\x12&\n" +
	"\x0fdest_table_name\x18\x01 \x01(\tR\rdestTableName\x12\x1b\n" +
	"\tthread_id\x18\x02 \x01(\tR\bthreadId\x12.\n" +
	"\x10identifier_field\x18\x03 \x01(\tH\x00R\x0fidentifierField\x88\x01\x01\x12R\n" +
	"\x06schema\x18\x04 \x03(\v2:.io.debezium.server.iceberg.rpc.IcebergPayload.SchemaFieldR\x06schema\x12\x18\n" +
	"\apayload\x18\x06 \x01(\tR\apayload\x12\x1c\n" +
	"\tnamespace\x18\a \x01(\tR\tnamespace\x12\x16\n" +
	"\x06upsert\x18\b \x01(\bR\x06upsert\x12h\n" +
	"\x10partition_fields\x18\n" +
	" \x03(\v2=.io.debezium.server.iceberg.rpc.IcebergPayload.PartitionFieldR\x0fpartitionFieldsB\x13\n" +
	"\x11_identifier_field\x1a:\n" +
	"\vSchemaField\x12\x19\n" +
	"\bice_type\x18\x01 \x01(\tR\aiceType\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x1aD\n" +
	"\x0ePartitionField\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x1c\n" +
	"\ttransform\x18\x02 \x01(\tR\ttransform\x1a\x92\x03\n" +
	"\tIceRecord\x12[\n" +
	"\x06fields\x18\x01 \x03(\v2C.io.debezium.server.iceberg.rpc.IcebergPayload.IceRecord.FieldValueR\x06fields\x12\x1f\n" +
	"\vrecord_type\x18\x02 \x01(\tR\n" +
	"recordType\x1a\x86\x02\n" +
	"\n" +
	"FieldValue\x12#\n" +
	"\fstring_value\x18\x01 \x01(\tH\x00R\vstringValue\x12\x1d\n" +
	"\tint_value\x18\x02 \x01(\x05H\x00R\bintValue\x12\x1f\n" +
	"\n" +
	"long_value\x18\x03 \x01(\x03H\x00R\tlongValue\x12!\n" +
	"\vfloat_value\x18\x04 \x01(\x02H\x00R\n" +
	"floatValue\x12#\n" +
	"\fdouble_value\x18\x05 \x01(\x01H\x00R\vdoubleValue\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x06 \x01(\bH\x00R\tboolValue\x12!\n" +
	"\vbytes_value\x18\a \x01(\fH\x00R\n" +
	"bytesValueB\a\n" +
	"\x05value\"\x8f\x01\n" +
	"\vPayloadType\x12\v\n" +
	"\aRECORDS\x10\x00\x12\n" +
	"\n" +
	"\x06COMMIT\x10\x01\x12\x11\n" +
	"\rEVOLVE_SCHEMA\x10\x02\x12\x0e\n" +
	"\n" +
	"DROP_TABLE\x10\x03\x12\x17\n" +
	"\x13GET_OR_CREATE_TABLE\x10\x04\x12\x18\n" +
	"\x14REFRESH_TABLE_SCHEMA\x10\x05\x12\x11\n" +
	"\rCLOSE_SESSION\x10\x06\"p\n" +
	"\x14RecordIngestResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12&\n" +
	"\x0folake_2pc_state\x18\x03 \x01(\tR\rolake2pcState\"\xe4\b\n" +
	"\fArrowPayload\x12L\n" +
	"\x04type\x18\x01 \x01(\x0e28.io.debezium.server.iceberg.rpc.ArrowPayload.PayloadTypeR\x04type\x12Q\n" +
	"\bmetadata\x18\x02 \x01(\v25.io.debezium.server.iceberg.rpc.ArrowPayload.MetadataR\bmetadata\x1a\xca\x03\n" +
	"\fFileMetadata\x12\x1b\n" +
	"\tfile_type\x18\x01 \x01(\tR\bfileType\x12\x1b\n" +
	"\tfile_path\x18\x02 \x01(\tR\bfilePath\x12!\n" +
	"\frecord_count\x18\x03 \x01(\x03R\vrecordCount\x12s\n" +
	"\x10partition_values\x18\x05 \x03(\v2H.io.debezium.server.iceberg.rpc.ArrowPayload.FileMetadata.PartitionValueR\x0fpartitionValues\x1a\xe7\x01\n" +
	"\x0ePartitionValue\x12\x1d\n" +
	"\tint_value\x18\x01 \x01(\x05H\x00R\bintValue\x12\x1f\n" +
	"\n" +
	"long_value\x18\x02 \x01(\x03H\x00R\tlongValue\x12#\n" +
	"\fstring_value\x18\x03 \x01(\tH\x00R\vstringValue\x12!\n" +
	"\vfloat_value\x18\x04 \x01(\x02H\x00R\n" +
	"floatValue\x12#\n" +
	"\fdouble_value\x18\x05 \x01(\x01H\x00R\vdoubleValue\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x06 \x01(\bH\x00R\tboolValueB\a\n" +
	"\x05value\x1aM\n" +
	"\x11FileUploadRequest\x12\x1b\n" +
	"\tfile_data\x18\x01 \x01(\fR\bfileData\x12\x1b\n" +
	"\tfile_path\x18\x02 \x01(\tR\bfilePath\x1a\xbf\x02\n" +
	"\bMetadata\x12&\n" +
	"\x0fdest_table_name\x18\x01 \x01(\tR\rdestTableName\x12\x1b\n" +
	"\tthread_id\x18\x02 \x01(\tR\bthreadId\x12^\n" +
	"\rfile_metadata\x18\x03 \x03(\v29.io.debezium.server.iceberg.rpc.ArrowPayload.FileMetadataR\ffileMetadata\x12d\n" +
	"\vfile_upload\x18\x04 \x01(\v2>.io.debezium.server.iceberg.rpc.ArrowPayload.FileUploadRequestH\x00R\n" +
	"fileUpload\x88\x01\x01\x12\x18\n" +
	"\apayload\x18\x06 \x01(\tR\apayloadB\x0e\n" +
	"\f_file_upload\"U\n" +
	"\vPayloadType\x12\x0f\n" +
	"\vUPLOAD_FILE\x10\x00\x12\x17\n" +
	"\x13REGISTER_AND_COMMIT\x10\x01\x12\x0e\n" +
	"\n" +
	"JSONSCHEMA\x10\x02\x12\f\n" +
	"\bFILEPATH\x10\x03\"\xe1\x01\n" +
	"\x13ArrowIngestResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\x12o\n" +
	"\x0eicebergSchemas\x18\x02 \x03(\v2G.io.debezium.server.iceberg.rpc.ArrowIngestResponse.IcebergSchemasEntryR\x0eicebergSchemas\x1aA\n" +
	"\x13IcebergSchemasEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\x8a\x01\n" +
	"\x13RecordIngestService\x12s\n" +
	"\vSendRecords\x12..io.debezium.server.iceberg.rpc.IcebergPayload\x1a4.io.debezium.server.iceberg.rpc.RecordIngestResponse2\x85\x01\n" +
	"\x12ArrowIngestService\x12o\n" +
	"\n" +
	"IcebergAPI\x12,.io.debezium.server.iceberg.rpc.ArrowPayload\x1a3.io.debezium.server.iceberg.rpc.ArrowIngestResponseB\x1dB\fRecordIngestZ\riceberg/protob\x06proto3"

var (
	file_records_ingest_proto_rawDescOnce sync.Once
	file_records_ingest_proto_rawDescData []byte
)

func file_records_ingest_proto_rawDescGZIP() []byte {
	file_records_ingest_proto_rawDescOnce.Do(func() {
		file_records_ingest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_records_ingest_proto_rawDesc), len(file_records_ingest_proto_rawDesc)))
	})
	return file_records_ingest_proto_rawDescData
}

var file_records_ingest_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_records_ingest_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_records_ingest_proto_goTypes = []any{
	(IcebergPayload_PayloadType)(0),                  // 0: io.debezium.server.iceberg.rpc.IcebergPayload.PayloadType
	(ArrowPayload_PayloadType)(0),                    // 1: io.debezium.server.iceberg.rpc.ArrowPayload.PayloadType
	(*IcebergPayload)(nil),                           // 2: io.debezium.server.iceberg.rpc.IcebergPayload
	(*RecordIngestResponse)(nil),                     // 3: io.debezium.server.iceberg.rpc.RecordIngestResponse
	(*ArrowPayload)(nil),                             // 4: io.debezium.server.iceberg.rpc.ArrowPayload
	(*ArrowIngestResponse)(nil),                      // 5: io.debezium.server.iceberg.rpc.ArrowIngestResponse
	(*IcebergPayload_Metadata)(nil),                  // 6: io.debezium.server.iceberg.rpc.IcebergPayload.Metadata
	(*IcebergPayload_SchemaField)(nil),               // 7: io.debezium.server.iceberg.rpc.IcebergPayload.SchemaField
	(*IcebergPayload_PartitionField)(nil),            // 8: io.debezium.server.iceberg.rpc.IcebergPayload.PartitionField
	(*IcebergPayload_IceRecord)(nil),                 // 9: io.debezium.server.iceberg.rpc.IcebergPayload.IceRecord
	(*IcebergPayload_IceRecord_FieldValue)(nil),      // 10: io.debezium.server.iceberg.rpc.IcebergPayload.IceRecord.FieldValue
	(*ArrowPayload_FileMetadata)(nil),                // 11: io.debezium.server.iceberg.rpc.ArrowPayload.FileMetadata
	(*ArrowPayload_FileUploadRequest)(nil),           // 12: io.debezium.server.iceberg.rpc.ArrowPayload.FileUploadRequest
	(*ArrowPayload_Metadata)(nil),                    // 13: io.debezium.server.iceberg.rpc.ArrowPayload.Metadata
	(*ArrowPayload_FileMetadata_PartitionValue)(nil), // 14: io.debezium.server.iceberg.rpc.ArrowPayload.FileMetadata.PartitionValue
	nil, // 15: io.debezium.server.iceberg.rpc.ArrowIngestResponse.IcebergSchemasEntry
}
var file_records_ingest_proto_depIdxs = []int32{
	0,  // 0: io.debezium.server.iceberg.rpc.IcebergPayload.type:type_name -> io.debezium.server.iceberg.rpc.IcebergPayload.PayloadType
	6,  // 1: io.debezium.server.iceberg.rpc.IcebergPayload.metadata:type_name -> io.debezium.server.iceberg.rpc.IcebergPayload.Metadata
	9,  // 2: io.debezium.server.iceberg.rpc.IcebergPayload.records:type_name -> io.debezium.server.iceberg.rpc.IcebergPayload.IceRecord
	1,  // 3: io.debezium.server.iceberg.rpc.ArrowPayload.type:type_name -> io.debezium.server.iceberg.rpc.ArrowPayload.PayloadType
	13, // 4: io.debezium.server.iceberg.rpc.ArrowPayload.metadata:type_name -> io.debezium.server.iceberg.rpc.ArrowPayload.Metadata
	15, // 5: io.debezium.server.iceberg.rpc.ArrowIngestResponse.icebergSchemas:type_name -> io.debezium.server.iceberg.rpc.ArrowIngestResponse.IcebergSchemasEntry
	7,  // 6: io.debezium.server.iceberg.rpc.IcebergPayload.Metadata.schema:type_name -> io.debezium.server.iceberg.rpc.IcebergPayload.SchemaField
	8,  // 7: io.debezium.server.iceberg.rpc.IcebergPayload.Metadata.partition_fields:type_name -> io.debezium.server.iceberg.rpc.IcebergPayload.PartitionField
	10, // 8: io.debezium.server.iceberg.rpc.IcebergPayload.IceRecord.fields:type_name -> io.debezium.server.iceberg.rpc.IcebergPayload.IceRecord.FieldValue
	14, // 9: io.debezium.server.iceberg.rpc.ArrowPayload.FileMetadata.partition_values:type_name -> io.debezium.server.iceberg.rpc.ArrowPayload.FileMetadata.PartitionValue
	11, // 10: io.debezium.server.iceberg.rpc.ArrowPayload.Metadata.file_metadata:type_name -> io.debezium.server.iceberg.rpc.ArrowPayload.FileMetadata
	12, // 11: io.debezium.server.iceberg.rpc.ArrowPayload.Metadata.file_upload:type_name -> io.debezium.server.iceberg.rpc.ArrowPayload.FileUploadRequest
	2,  // 12: io.debezium.server.iceberg.rpc.RecordIngestService.SendRecords:input_type -> io.debezium.server.iceberg.rpc.IcebergPayload
	4,  // 13: io.debezium.server.iceberg.rpc.ArrowIngestService.IcebergAPI:input_type -> io.debezium.server.iceberg.rpc.ArrowPayload
	3,  // 14: io.debezium.server.iceberg.rpc.RecordIngestService.SendRecords:output_type -> io.debezium.server.iceberg.rpc.RecordIngestResponse
	5,  // 15: io.debezium.server.iceberg.rpc.ArrowIngestService.IcebergAPI:output_type -> io.debezium.server.iceberg.rpc.ArrowIngestResponse
	14, // [14:16] is the sub-list for method output_type
	12, // [12:14] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_records_ingest_proto_init() }
func file_records_ingest_proto_init() {
	if File_records_ingest_proto != nil {
		return
	}
	file_records_ingest_proto_msgTypes[4].OneofWrappers = []any{}
	file_records_ingest_proto_msgTypes[8].OneofWrappers = []any{
		(*IcebergPayload_IceRecord_FieldValue_StringValue)(nil),
		(*IcebergPayload_IceRecord_FieldValue_IntValue)(nil),
		(*IcebergPayload_IceRecord_FieldValue_LongValue)(nil),
		(*IcebergPayload_IceRecord_FieldValue_FloatValue)(nil),
		(*IcebergPayload_IceRecord_FieldValue_DoubleValue)(nil),
		(*IcebergPayload_IceRecord_FieldValue_BoolValue)(nil),
		(*IcebergPayload_IceRecord_FieldValue_BytesValue)(nil),
	}
	file_records_ingest_proto_msgTypes[11].OneofWrappers = []any{}
	file_records_ingest_proto_msgTypes[12].OneofWrappers = []any{
		(*ArrowPayload_FileMetadata_PartitionValue_IntValue)(nil),
		(*ArrowPayload_FileMetadata_PartitionValue_LongValue)(nil),
		(*ArrowPayload_FileMetadata_PartitionValue_StringValue)(nil),
		(*ArrowPayload_FileMetadata_PartitionValue_FloatValue)(nil),
		(*ArrowPayload_FileMetadata_PartitionValue_DoubleValue)(nil),
		(*ArrowPayload_FileMetadata_PartitionValue_BoolValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_records_ingest_proto_rawDesc), len(file_records_ingest_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_records_ingest_proto_goTypes,
		DependencyIndexes: file_records_ingest_proto_depIdxs,
		EnumInfos:         file_records_ingest_proto_enumTypes,
		MessageInfos:      file_records_ingest_proto_msgTypes,
	}.Build()
	File_records_ingest_proto = out.File
	file_records_ingest_proto_goTypes = nil
	file_records_ingest_proto_depIdxs = nil
}
